/**
 * TypeScript shapes mirroring the FastAPI `/api/...` responses in
 * `app/api/routes.py`. When you add a field to a route's response, add
 * it here too — that's the only contract between backend and mobile.
 */

export type IndustrySummary = {
  name: string;
  slug: string;
  ticker_count: number;
  latest_analyzed: string; // YYYY-MM-DD
};

export type IndustryListResponse = {
  industries: IndustrySummary[];
  total_tickers: number;
  updated_at: string; // ISO-8601
};

export type ValidationStatus = 'ok' | 'info' | 'warn' | 'error';

export type TickerRow = {
  ticker: string;
  name: string;
  sector: string;
  industry: string;
  market_cap: number | null;
  ttm_pe: number | null;
  ttm_pocf: number | null;
  ps: number | null;
  pb: number | null;
  latest_q_ni: number | null;
  latest_q_ocf: number | null;
  analyzed_date: string;
  status: ValidationStatus;
};

export type IndustryDetailResponse = {
  industry: string;
  slug: string;
  ticker_count: number;
  tickers: TickerRow[];
  /** LLM-generated daily summary written when this industry was scanned.
   * Empty string for industries that pre-date the summary-persistence
   * feature (older daily-log entries lack the field). */
  summary_md: string;
  /** Date of the most recent batch that scanned this industry. */
  summary_date: string;
};

export type Snapshot = {
  // Headline + valuation multiples
  market_cap: number | null;
  ttm_pe: number | null;
  static_pe: number | null;
  ev_revenue: number | null;
  pb: number | null;
  ps: number | null;
  p_fcf: number | null;
  ttm_pocf: number | null;
  // Health / profitability ratios — stored as decimals (0.25 = 25%)
  debt_asset: number | null;
  gross_margin: number | null;
  op_margin: number | null;
  net_margin: number | null;
  roe: number | null;
  roa: number | null;
  // Annualized dividend per share in dollars (0.0 for non-payers, null when shares missing)
  dividend_rate: number | null;
};

export type Period = {
  period: string;       // ISO date for the period end
  items: Record<string, number | null>;
  sources?: Record<string, string>;
};

export type Statements = {
  income_statement: Period[];
  balance_sheet: Period[];
  cash_flow: Period[];
};

export type NarrativeSource = {
  title?: string;
  url?: string;
  snippet?: string;
  published_date?: string | null;
};

export type Narrative = {
  text: string;
  model: string | null;
  provider: string | null;
  sources: NarrativeSource[];
  rerun_at: string | null;
};

export type ValidationIssue = {
  severity: 'info' | 'warn' | 'error';
  rule: string;
  detail: string;
};

export type Validation = {
  status: ValidationStatus;
  issues: ValidationIssue[];
};

export type TickerDetail = {
  ticker: string;
  name: string;
  sector: string;
  industry: string;
  exchange: string;
  country: string;
  business_overview: string;
  classification: Record<string, string>;
  classification_meta: { primary_category?: string; logic_summary?: string };
  snapshot: Snapshot;
  annual: Statements;
  quarterly: Statements;
  narrative: Narrative;
  validation: Validation;
  analyzed_date: string;
};

export type PricePoint = { date: string; close: number; volume?: number };

export type PriceHistoryResponse = {
  ticker: string;
  period: string | null;
  interval: string | null;
  data: PricePoint[];
};

export type DigestResponse = {
  date: string;
  industries: string[];
  ticker_count: number;
  /**
   * Markdown-formatted "stories of the day" paragraph generated by the
   * digest_summary LLM prompt. Empty string when no persisted digest
   * exists yet (the route falls back to composing from the daily-scan
   * log, which has no summary).
   */
  summary_md: string;
  tickers: TickerRow[];
  /** ISO-8601 timestamp the digest JSON was written, or null if the
   * fallback path served. */
  generated_at: string | null;
};

/** Compact summary of one past daily-scan batch — used by the home
 * screen's vertical stack of digest banners. */
export type RecentDigest = {
  date: string;
  industries: string[];
  /** URL slug of the (first) industry, for navigating to its ticker list. */
  slug: string | null;
  ticker_count: number;
  /** Only populated for the latest entry (matches the persisted digest file). */
  summary_md: string;
  is_latest: boolean;
};

export type RecentDigestsResponse = {
  digests: RecentDigest[];
};
